name: CI

env:
  IMAGE_TAG: vocabs-dumps

on:
  push:
    branches: [main]

jobs:
  build_and_push_to_registry:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Put dockerfile in main directory
        run: |
          cp -r ./dockerfiles/Dockerfile ./Dockerfile
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/acdh-oeaw/${{ env.IMAGE_TAG }}
  deploy_downloads:
    needs: build_and_push_to_registry
    name: Deploy to cluster downloads container
    runs-on: ubuntu-latest
    steps:
    - name: Rancher Deploy Action
      run: |
        curl -i -X POST "${{ secrets.RANCHER_URL }}?action=redeploy" -H "Authorization: Bearer ${{ secrets.RANCHER_BEARER_TOKEN }}"

